[tool.poetry]
name = "lea"
version = "0.1.0"
description = "A minimalist alternative to dbt"
authors = ["Max Halford <maxhalford25@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
sqlglot = "^18.7.0"
Jinja2 = "^3.1.2"
typer = "^0.6.1"
google-cloud-bigquery = "^3.3.2"
db-dtypes = "^1.0.3"
requests = "^2.28.1"
python-dotenv = "^0.21.0"
rich = "^12.6.0"
tabulate = "^0.9.0"
pandas-gbq = "^0.19.2"
duckdb = "^0.8.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.21.2"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lea = "lea.main:app"
