[tool.poetry]
name = "lea"
version = "0.1.0"
description = "A minimalist alternative to dbt"
authors = ["Max Halford <maxhalford25@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
sqlglot = "^18.10.0"
Jinja2 = "^3.1.2"
typer = "^0.9.0"
google-cloud-bigquery = "^3.11.4"
db-dtypes = "^1.1.1"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
rich = "^13.5.3"
tabulate = "^0.9.0"
pandas-gbq = "^0.19.2"
duckdb = "^0.9.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.21.2"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lea = "lea.main:app"
